
import __ASTRO_IMAGE_IMPORT_200DXS from "./Cloud-gravity/assets/Revenue_vs_Cloud_Cost_Growth__Expected_vs_Actual_(4-Year_Startup_Scaling_Journey).png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcloud-cost-gravity.md";
import __ASTRO_IMAGE_IMPORT_1I1Wgl from "./Cloud-gravity/assets/Cloud_Cost_Composition_by_Adopter_Level__Baseline_vs_Waste_vs_Discount_Premium_(%_of_Revenue).png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcloud-cost-gravity.md";
import __ASTRO_IMAGE_IMPORT_1hl0wQ from "./Cloud-gravity/assets/Cloud_Cost_Outcomes_Achievement__2020_vs_2023_by_Adoption_Level.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcloud-cost-gravity.md";
import __ASTRO_IMAGE_IMPORT_ZgySWE from "./chicken-egg/assets/163.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-chicken-and-egg-problem.md";
import __ASTRO_IMAGE_IMPORT_1mnVoq from "./chicken-egg/assets/166.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-chicken-and-egg-problem.md";
import __ASTRO_IMAGE_IMPORT_Z1pDELB from "./chicken-egg/assets/164.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-chicken-and-egg-problem.md";
import __ASTRO_IMAGE_IMPORT_2vsHdn from "./chicken-egg/assets/165.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-chicken-and-egg-problem.md";
import __ASTRO_IMAGE_IMPORT_djazt from "./chicken-egg/assets/167.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-chicken-and-egg-problem.md";
import __ASTRO_IMAGE_IMPORT_Z1Ub7QF from "./Ed-tech/assets/edtech_cac_chart.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-indian-edtech-collapsed.md";
import __ASTRO_IMAGE_IMPORT_nXLGh from "./Ed-tech/assets/retention_comparison.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-indian-edtech-collapsed.md";
import __ASTRO_IMAGE_IMPORT_ZLgzlw from "./Ed-tech/assets/edtech_revenue_cac_chart.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-indian-edtech-collapsed.md";
import __ASTRO_IMAGE_IMPORT_Z10aVKL from "./Ed-tech/assets/edtech_vs_offline_comparison.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-indian-edtech-collapsed.md";
export default new Map([["./Cloud-gravity/assets/Revenue_vs_Cloud_Cost_Growth__Expected_vs_Actual_(4-Year_Startup_Scaling_Journey).png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcloud-cost-gravity.md", __ASTRO_IMAGE_IMPORT_200DXS], ["./Cloud-gravity/assets/Cloud_Cost_Composition_by_Adopter_Level__Baseline_vs_Waste_vs_Discount_Premium_(%_of_Revenue).png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcloud-cost-gravity.md", __ASTRO_IMAGE_IMPORT_1I1Wgl], ["./Cloud-gravity/assets/Cloud_Cost_Outcomes_Achievement__2020_vs_2023_by_Adoption_Level.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcloud-cost-gravity.md", __ASTRO_IMAGE_IMPORT_1hl0wQ], ["./chicken-egg/assets/163.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-chicken-and-egg-problem.md", __ASTRO_IMAGE_IMPORT_ZgySWE], ["./chicken-egg/assets/166.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-chicken-and-egg-problem.md", __ASTRO_IMAGE_IMPORT_1mnVoq], ["./chicken-egg/assets/164.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-chicken-and-egg-problem.md", __ASTRO_IMAGE_IMPORT_Z1pDELB], ["./chicken-egg/assets/165.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-chicken-and-egg-problem.md", __ASTRO_IMAGE_IMPORT_2vsHdn], ["./chicken-egg/assets/167.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-chicken-and-egg-problem.md", __ASTRO_IMAGE_IMPORT_djazt], ["./Ed-tech/assets/edtech_cac_chart.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-indian-edtech-collapsed.md", __ASTRO_IMAGE_IMPORT_Z1Ub7QF], ["./Ed-tech/assets/retention_comparison.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-indian-edtech-collapsed.md", __ASTRO_IMAGE_IMPORT_nXLGh], ["./Ed-tech/assets/edtech_revenue_cac_chart.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-indian-edtech-collapsed.md", __ASTRO_IMAGE_IMPORT_ZLgzlw], ["./Ed-tech/assets/edtech_vs_offline_comparison.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fwhy-indian-edtech-collapsed.md", __ASTRO_IMAGE_IMPORT_Z10aVKL]]);
		